# Generated by Django 4.0 on 2021-12-17 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0002_products_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='cat_img'),
            preserve_default=False,
        ),
    ]
