# Generated by Django 4.0 on 2021-12-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0003_category_cat_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_img',
        ),
    ]
