# Generated by Django 4.0 on 2021-12-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0004_remove_category_cat_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(default='', upload_to='cat_img'),
        ),
    ]
