# Generated by Django 4.0 on 2021-12-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0005_category_cat_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img2',
            field=models.ImageField(default='', upload_to='product'),
        ),
        migrations.AddField(
            model_name='products',
            name='img3',
            field=models.ImageField(default='', upload_to='product'),
        ),
        migrations.AddField(
            model_name='products',
            name='img4',
            field=models.ImageField(default='', upload_to='product'),
        ),
        migrations.AddField(
            model_name='products',
            name='thumb1',
            field=models.ImageField(default='', upload_to='product'),
        ),
        migrations.AddField(
            model_name='products',
            name='thumb2',
            field=models.ImageField(default='', upload_to='product'),
        ),
        migrations.AddField(
            model_name='products',
            name='thumb3',
            field=models.ImageField(default='', upload_to='product'),
        ),
        migrations.AddField(
            model_name='products',
            name='thumb4',
            field=models.ImageField(default='', upload_to='product'),
        ),
    ]
