# Generated by Django 4.0 on 2021-12-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0006_products_img2_products_img3_products_img4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='thumb1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='thumb2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='thumb3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='thumb4',
        ),
    ]
