# Generated by Django 4.0 on 2022-01-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='country',
            field=models.CharField(default='India', max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='state',
            field=models.CharField(default='Kerala', max_length=30),
        ),
    ]
