# Generated by Django 4.0 on 2022-01-08 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
