# Generated by Django 4.0 on 2022-01-10 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_ordertable_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.DeleteModel(
            name='OrderTable',
        ),
    ]
