# Generated by Django 4.0 on 2022-01-10 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0007_remove_products_img2_remove_products_img3_and_more'),
        ('cart', '0009_ordertable_orderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitapp.products'),
        ),
    ]
