# Generated by Django 4.0 on 2022-01-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_orderdetails_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.DeleteModel(
            name='OrderTable',
        ),
    ]
