# Generated by Django 4.0 on 2022-01-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_orderdetails_tot_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='tot_price',
        ),
    ]
