# Generated by Django 4.0 on 2022-01-18 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_remove_orderdetails_tot_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
