# Generated by Django 4.0 on 2022-01-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_orderdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
