# Generated by Django 4.0 on 2022-01-18 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_delete_orderdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderTable',
        ),
    ]
